# Copyright 2017-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.1.5

EAPI=6

CRATES="
ansi_term-0.11.0
atty-0.2.11
bitflags-1.0.4
cbindgen-0.6.3
cfg-if-0.1.5
clap-2.32.0
cloudabi-0.0.3
fuchsia-zircon-0.3.3
fuchsia-zircon-sys-0.3.3
itoa-0.4.3
libc-0.2.43
log-0.4.5
proc-macro2-0.4.19
quote-0.3.15
quote-0.6.8
rand-0.5.5
rand_core-0.2.1
redox_syscall-0.1.40
redox_termios-0.1.1
remove_dir_all-0.5.1
ryu-0.2.6
serde-1.0.78
serde_derive-1.0.21
serde_derive_internals-0.17.0
serde_json-1.0.27
strsim-0.7.0
syn-0.11.11
syn-0.14.9
synom-0.11.3
tempfile-3.0.3
termion-1.5.1
textwrap-0.10.0
toml-0.4.6
unicode-width-0.1.5
unicode-xid-0.0.4
unicode-xid-0.1.0
vec_map-0.8.1
winapi-0.3.5
winapi-i686-pc-windows-gnu-0.4.0
winapi-x86_64-pc-windows-gnu-0.4.0
"

inherit cargo

DESCRIPTION="A tool for generating C bindings to Rust code."
HOMEPAGE="https://github.com/eqrion/cbindgen/"
SRC_URI="$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
LICENSE="MPL-2.0" # Update to proper Gentoo format
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=""
RDEPEND=""
