#!/bin/sh

. /usr/share/initramfs-tools/hook-functions

copy_file "osk-sdl config" /etc/osk.conf /etc/osk.conf
copy_exec /usr/bin/osk-sdl /usr/bin/osk-sdl
copy_exec /usr/share/initramfs-tools/script/local-top/osk-sdl /scripts/local-top/osk-sdl
copy_exec /usr/share/initramfs-tools/script/local-block/osk-sdl /scripts/local-block/osk-sdl
copy_file "crypttab" /etc/crypttab /etc/crypttab

copy_exec /lib/aarch64-linux-gnu/dri/sun4i-drm_dri.so
copy_exec /lib/aarch64-linux-gnu/libglapi.so.*
copy_exec /lib/aarch64-linux-gnu/libcogl.so.*

libdir="/lib/aarch64-linux-gnu/"
find -L "$libdir" -name "libGL*.so*" -o -name "libEGL*.so*" -o -name "libEGL_mesa.so*" -type f | while read -r so; do
    copy_exec "$so"
done

copy_file "json" /usr/share/glvnd/egl_vendor.d/50_mesa.json
exit 0
